env:
  browser: true
  es2021: true
  node: true
extends:
  - 'plugin:react/recommended'
  - airbnb
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
plugins:
  - react
rules:
  react/jsx-props-no-spreading: off
  react/react-in-jsx-scope: off
  max-classes-per-file: off
  no-param-reassign: off
  quotes: off
  react/no-unescaped-entities: off
  react/jsx-one-expression-per-line: off
