version: 2.1

jobs:
  build:
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.2
      - run:
          name: test
          command: |
            npm install
            /app/node_modules/@sentry/cli/sentry-cli projects -o openmaraude list

workflows:
  version: 2

  # Build artifacts, only run for tags.
  test:
    jobs:
      - build
