version: 2.1

jobs:
  build:
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.2
      - run:
          name: Install build dependencies
          command: |
            sudo apt -qq update
            sudo apt install graphviz
      - run:
          name: Build and publish docker Image to hub.docker.com
          command: |
            echo token: ${SENTRY_AUTH_TOKEN}

workflows:
  version: 2

  # Run unittest
  test:
    jobs:
      - build

  # Build artifacts, only run for tags.
  artifacts:
    jobs:
      - build:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
